# Generated by Django 2.0 on 2020-04-20 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('delete_at', models.DateTimeField(help_text='删除时间', null=True, verbose_name='删除时间')),
                ('article_title', models.CharField(help_text='文章的标题', max_length=120, verbose_name='文章的标题')),
                ('article_content', models.TextField(help_text='文章的正文', verbose_name='文章的正文')),
                ('reply_count', models.IntegerField(default=0, help_text='评论数', verbose_name='评论数')),
                ('like_count', models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数')),
                ('user', models.ForeignKey(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL, verbose_name='文章发表用户名')),
            ],
            options={
                'verbose_name': 'article',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('delete_at', models.DateTimeField(help_text='删除时间', null=True, verbose_name='删除时间')),
                ('reply_username', models.CharField(help_text='评论的用户名', max_length=64, verbose_name='评论的用户名')),
                ('reply_content', models.TextField(help_text='评论内容', verbose_name='评论内容')),
                ('article', models.ForeignKey(help_text='文章的id', on_delete='models.CASCADE', to='user.Article', verbose_name='文章的id')),
            ],
            options={
                'verbose_name': 'comment',
                'db_table': 'comment',
            },
        ),
    ]
