# Generated by Django 2.0 on 2020-04-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.IntegerField(default=1, max_length=24),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.IntegerField(choices=[(0, '职员'), (1, '非职员')]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_superuser',
            field=models.IntegerField(choices=[(0, '普通账号'), (1, '超级管理员')], default=0),
        ),
    ]
