# Generated by Django 2.0 on 2020-04-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='delete_at',
            field=models.DateTimeField(help_text='删除时间', null=True, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_at',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='delete_at',
            field=models.DateTimeField(help_text='删除时间', null=True, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='update_at',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
    ]
