# Generated by Django 2.0 on 2020-04-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200430_1128'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_article_56e73b_idx',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='article_id',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article_id'], name='comment_article_8c2b06_idx'),
        ),
    ]
